### ISSUE TITLE
外观大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#110]
## 设计稿与UI

https://www.figma.com/design/FQpOxDtTICRpEKF83mRfuj/PVX3.0?node-id=1500-1499&t=JZWJnwPeclbpxv6L-0
需向设计师胧月请求权限

- [ ] 已完成

**Comment by iRuxu** [comment]
## 入口

侧边栏新增入口，外观大全
https://www.figma.com/design/FQpOxDtTICRpEKF83mRfuj/PVX3.0?node-id=408-6274&t=JZWJnwPeclbpxv6L-0
应用标识符  外观：“exterior”

- [x] 已完成

**Comment by iRuxu** [comment]
## 接口

来自不咕

https://node.jx3box.com/documentation

<img width="1024" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/4e8b72e1-853d-4129-8360-dcbaed8a17c6">

- [ ] 已完成

**Comment by iRuxu** [comment]
## 资源问题

外观图片资源请和后端协商，由他和负责数据源的受姐姐沟通

- [ ] 已完成

**Comment by iRuxu** [comment]
## 黑市联动部分

和黑市的部分，只要做好UI在那就行
数据等后续做黑市的时候加

- [ ] 已完成

**Comment by iRuxu** [comment]
## 侧边栏
<img width="956" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/325634e3-cfef-4b74-98c9-db765c5e2642">

访问的是体型，为什么高亮的是外观大全

- [ ] 已完成

**Comment by iRuxu** [comment]
## 侧边栏2
<img width="520" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/9f58615a-1f08-46e6-aebd-ace7766ff259">

- [ ] 已完成

**Comment by TiAmo-code** [comment]
> ## 侧边栏
> <img alt="image" width="956" src="https://private-user-images.githubusercontent.com/8476969/333838619-325634e3-cfef-4b74-98c9-db765c5e2642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMjY3ODcsIm5iZiI6MTcxNzIyNjQ4NywicGF0aCI6Ii84NDc2OTY5LzMzMzgzODYxOS0zMjU2MzRlMy1jZmVmLTRiNzQtOThjOS1kYjc2NWM1ZTI2NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDFUMDcyMTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U2MTVhMjBkMzAwYjA4OWY2NWYwMWE2YjkxODY4MDEzYTU1YzMwZDFmZjVlNGIyZmI3MTk3MjdkYWVhODI0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OE5_L7Vc4KjxknpHkiLRQQvBODsGjNzpuYnKg6uZID8">
> 访问的是体型，为什么高亮的是外观大全
> 
> * [ ]  已完成

需要提供下侧边栏外观大全的图标
