### ISSUE TITLE
pvx优化需求

### ISSUE THREAD

**Issue by zixuan1986** [JX3BOX/pvx_v1#113]
[界面调整需求 - 盾咚 - 20230905.pptx](https://github.com/JX3BOX/pvx/files/12518418/-.-.20230905.pptx)
## 家园
<img width="1439" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/f352baa6-22eb-4c10-9f58-869f06f4a6b1">

- [ ] 已完成

**Comment by nierssaxa** [comment]
像这种跳转到其他网页的，应当加一个图标在后面
![image](https://github.com/JX3BOX/pvx/assets/97571785/bb4e3637-4c2e-4981-89cd-f0a3cc16f194)
可以修改宽度
