### ISSUE TITLE
脸型数据类型扩展

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#115]
根据产品给的文档，编写前端这里，和后端（小胡的jx3box-api）仓库的开发需求文档

新字段为 `is_new_face`
https://github.com/JX3BOX/jx3box-api/issues/277

- [x] 已完成

**Comment by Kaviilee** [comment]
## 去除编辑推荐

![image](https://github.com/JX3BOX/pvx/assets/25825282/c4dcdceb-923b-4c1c-b459-49efd1c90067)

- [x] 已完成

**Comment by Kaviilee** [comment]
## 顶部筛选
筛选部分细化
![image](https://github.com/JX3BOX/pvx/assets/25825282/519cbd4b-4bec-42f6-b362-93e609981b7f)

- [x] 已完成

**Comment by Kaviilee** [comment]
## 列表展示项
![image](https://github.com/JX3BOX/pvx/assets/25825282/2ea7b441-59ca-4b82-a349-edf8cef34486)
改动点如下：
- 【编辑推荐】和【收费】由原先的文字显示改为图标形式显示，居右上侧，星标为【编辑推荐】，钱币为【收费】
- **正式服** 左侧常驻【写实】或者【写意】，如果支持【可新建】则同时显示。
- **怀旧服** 不存在写实或者写意，所以当支持【可新建】则显示【可新建】，右侧同正式服一致
- 鼠标移入时新增动画 `eas-out 300ms`

Figma权限找胧月

- [x] 已完成

**Comment by Kaviilee** [comment]
## 详情页

### 第一屏

无论是免费还是收费都分成左右区域。（这是不同于现行的）

#### 收费
![image](https://github.com/JX3BOX/pvx/assets/25825282/8f675d29-375c-4723-92d8-f0205a89973b)
- 未购买时显示购买的样式，已购买显示下载按钮
- 已登头条改为在右侧底部显示

#### 免费
![image](https://github.com/JX3BOX/pvx/assets/25825282/2aa42ef0-8e01-4f67-92f6-71d5c06bbf80)

- 前端可以将文件打包导出 [JSZip](https://stuk.github.io/jszip/) + [FileSaver.js](https://github.com/eligrey/FileSaver.js)

- [x] 已完成
---------------
### 独家数据分析
样式有较大修改和细化

#### 已购买或者免费数据
![image](https://github.com/JX3BOX/pvx/assets/25825282/e2655509-3deb-4536-bb62-5c30019018d2)
需要多一个下载按钮

**注意**：数据分析项的 slider 更改为不可以拖动
-----------------
**妆容** 改为表格样式显示
![image](https://github.com/JX3BOX/pvx/assets/25825282/91921e0e-b07d-4382-8853-f35a4dad644e)

#### 未购买数据
![image](https://github.com/JX3BOX/pvx/assets/25825282/ee07ebbc-f7db-45d1-8c3c-2a2d881c9219)

- [x] 已完成
-----------------------------
### 关于作者
![image](https://github.com/JX3BOX/pvx/assets/25825282/16b93d73-25c0-4e57-8a22-926dd9b95b48)
需要实装装扮

- [x] 已完成
