### ISSUE TITLE
捏脸优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#125]
https://docs.qq.com/doc/DSmhjcWt6WHZycGhU

有一些样式优化，具体和胧月沟通，注意要看下手机适配

**Comment by iRuxu** [comment]
<img width="312" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/d42ed7b7-51c9-4e8f-b040-f652faa43147">

- [x] 已完成

**Comment by nierssaxa** [comment]
## 主页
![image](https://github.com/JX3BOX/pvx/assets/97571785/2d1fb5c1-c9ce-4c42-8f05-09d010d4dc4b)
top bar的宽度自适应

- [x] 已完成

**Comment by nierssaxa** [comment]
## 主页
![ebd19faae672c1813737a3b3c2e53d96](https://github.com/JX3BOX/pvx/assets/97571785/7c61fee2-89e8-44e5-a4b5-caed3a2f684e)
鼠标移入的过程动画做了，鼠标移出的没做

- [x] 已完成

**Comment by nierssaxa** [comment]
## 主页
手机版的topbar 样式变化没做
![image](https://github.com/JX3BOX/pvx/assets/97571785/f99ed28e-b803-4708-a8e1-1db717d9f1e2)
![image](https://github.com/JX3BOX/pvx/assets/97571785/f985d85b-f9ed-47bf-950e-d2628e3de370)

- [x] 已完成

**Comment by nierssaxa** [comment]
## 主页
手机版选择体型后，图片从宽度自适应的长方形变为等比放大的正方形
![image](https://github.com/JX3BOX/pvx/assets/97571785/44357911-096a-4143-80b6-1d03a11b10b3)

- [ ] 已完成

**Comment by nierssaxa** [comment]
## 内页
![4de7ba9d1f6b5a1b075f84b5638ffbf6](https://github.com/JX3BOX/pvx/assets/97571785/dfd56e57-1cda-4649-a368-11bf39b14118)
阴影没加
![image](https://github.com/JX3BOX/pvx/assets/97571785/c5f65999-bf3c-491b-9ff4-4ac738f8088b)

- [x] 已完成

**Comment by nierssaxa** [comment]
### 内页
背景色和阴影都不对
![image](https://github.com/JX3BOX/pvx/assets/97571785/7f02604d-c8f2-486a-972b-c15024e64167)
![image](https://github.com/JX3BOX/pvx/assets/97571785/5dc921bc-c719-4094-b305-70e62300bfd5)
![image](https://github.com/JX3BOX/pvx/assets/97571785/fa15ab90-8b90-46c1-8f1f-31583b368188)

- [x] 已完成

**Comment by nierssaxa** [comment]
## 内容
1.去掉这两个
![81aedc89767df323f3ab4986c0e80973](https://github.com/JX3BOX/pvx/assets/97571785/8dcaccb8-e2c0-4153-a3af-8672f06b8661)
2.按照figma新增数据清洗
![d98948fc4ad6d06e9e5fdb204909c557](https://github.com/JX3BOX/pvx/assets/97571785/d4608365-153d-421f-81b9-89e771222939)
3.再把这两个放到数据清洗里面
![8228316bd035ce7b6039c8b690ef7379](https://github.com/JX3BOX/pvx/assets/97571785/3e64d3b5-859e-4d0e-b4d4-7e2ae743ef15)

- [x] 已完成

**Comment by nierssaxa** [comment]
## 内页
![image](https://github.com/JX3BOX/pvx/assets/97571785/81d8b930-e476-46d2-91d5-0fe01bd963b1)
没有可以点的项目，这里的手型去掉

- [x] 已完成

**Comment by nierssaxa** [comment]
## 内页
![image](https://github.com/JX3BOX/pvx/assets/97571785/fa7498ee-491c-45b1-810c-a0b5547f60b2)
两行之间的间距为10px

- [x] 已完成

**Comment by nierssaxa** [comment]
## 内页

手机内页的数据分析的二级标题和妆容都没有做自适应
figma已补样式
![image](https://github.com/JX3BOX/pvx/assets/97571785/303d64f4-4665-446a-bc06-40cd33cfdf5a)

- [x] 已完成

**Comment by nierssaxa** [comment]
## 内页
https://test.jx3box.com/face/3118
底部作者的其他脸型，要计算浏览器宽度，不要出现需要左右滑动的情况
![image](https://github.com/JX3BOX/pvx/assets/97571785/46cc7be9-587a-49e6-be3a-85463093e281)

- [x] 已完成
