### ISSUE TITLE
pvx3首页 + 坐骑 + 家具

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#135]
https://www.figma.com/file/FQpOxDtTICRpEKF83mRfuj/PVX3.0?type=design&node-id=260-12427&mode=design&t=HmpHMH9HuKM4p07u-0

**Comment by zixuan1986** [comment]
![b1b194387ddcbfa2626c6691a2fd826b](https://github.com/JX3BOX/pvx/assets/40552272/8426cb6b-7584-47bc-9ea1-85ff8614ea6b)
按钮间隔
- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="976" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/bd5e6c26-bf42-4dfc-a1d0-fe1d75f1b694">
检查一下图片对应的key是否正确
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="1673" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/b3118b56-74d2-41c2-8480-e9219583fca2">
物品icon已换接口，需要修复

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="430" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/34642b24-6893-4a02-a4f3-77b142e690cc">

- [x] 同上

**Comment by zixuan1986** [comment]
<img width="899" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/15d61c61-e3c1-4459-bfa1-07e0f09ccf02">

tabs错位

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="1625" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/fc206d94-3129-4bc2-b794-eed0c818bf78">
添加白色的背景底色

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="681" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/efd3b79c-da17-4188-8860-94c83ac3e448">
模拟ipad的tabs错位

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="619" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/7ff82c22-d034-488f-95cf-e00d78078f28">

还是tabs的问题，需要适配ipad
- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="785" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/f23d37a3-48ee-44f8-8313-ecb190789050">
坐骑页面适配

- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="591" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/6146c3ec-0b6c-4610-9009-1d36375b99c0">
这里顶格了，需要给个间隔

- [x] 已完成

**Comment by zixuan1986** [comment]
<img width="718" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/f32d863f-c9ce-4a58-afae-da2d0ca074cc">
书籍的适配，应该是和上上层通用的样式
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="563" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/f023eb4c-f162-4ea3-b033-482cd2286974">
<img width="588" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/60f4b6d9-0226-439f-86ba-a053491d4481">

手机端适配
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="425" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/8f416d15-5c21-4442-90e0-c5b79b2cc9a1">
手机端可以稍微调整一下高度变矮些
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="558" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/e6caf1d9-f152-40b4-a2b8-b2a163ea5851">
按钮问题
 
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="739" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/67347c5a-6d34-4344-b136-defb24052ffc">
<img width="461" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/dfdb8028-d720-4d57-a666-67ecf14b7f8c">

tabs调整不要justify-content: space-between
模块拉伸至100%

- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="616" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/9e133580-966f-4e35-a529-aa11bcd46daa">

- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="433" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/54f3c4ab-7560-4816-952b-570914092295">
压变形了
- [ ] 已完成

**Comment by zixuan1986** [comment]
<img width="400" alt="image" src="https://github.com/JX3BOX/pvx/assets/40552272/90912909-e7b2-4ebe-ab08-0fa13a176e3c">

- [ ] 已完成
