### ISSUE TITLE
PVX优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#140]
<img width="1356" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/3d089c2b-07e9-4755-87d7-7f16aa8a3882">

- [x] 已完成

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/8a314d55-dc0b-467b-ae68-aaa9376d761b)

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/859ebe3a-fc24-4349-945c-43c8f9ae19a7)
