### ISSUE TITLE
奇遇相关优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#16]
## 奇遇列表页的宠物跳转
当一个奇遇是宠物奇遇时，直接跳转至宠物的页面（方便看宠物地图等）。

- [x] 已完成

**Comment by iRuxu** [comment]
## 宠物单页的奇遇触发模块增加限定条件
只有当该宠物是一个奇遇宠物时，才显示底部的触发记录模块。

- [x] 已完成

**Comment by iRuxu** [comment]
## 游戏内宠物密鉴跳转
以下为流年反馈

在游戏内点击宠物图标，想知道怎么获取到这个宠物，但是跳转的成就是错误的

如下
![image](https://user-images.githubusercontent.com/8476969/151191810-33988d8e-9084-4b67-b7aa-1a5cc5c1b794.png)


点击以后跳转到的是成就【命中注定】召唤一次土土
![image](https://user-images.githubusercontent.com/8476969/151191826-fab6e9f8-c667-4bc7-8dd7-d5b0ee686b6a.png)


而正常的需求是怎么获取到，应该跳到如果获取这个宠物
![image](https://user-images.githubusercontent.com/8476969/151191849-b70a4125-0a11-4f82-824f-ebfcc3519016.png)


------------------------
https://github.com/JX3BOX/game
得让游戏内的宠物打开后，要么打开奇遇攻略，要么打开物品攻略。

- [x] 已完成

**Comment by Kaviilee** [comment]
> ## 奇遇列表页的宠物跳转
> 当一个奇遇是宠物奇遇时，直接跳转至宠物的页面（方便看宠物地图等）。
> 
> * [x]  已完成

无法实现

**Comment by Kaviilee** [comment]
> ## 奇遇列表页的宠物跳转
> 当一个奇遇是宠物奇遇时，直接跳转至宠物的页面（方便看宠物地图等）。
> 
> * [x]  已完成

无法完成

**Comment by Kaviilee** [comment]
> ## 宠物单页的奇遇触发模块增加限定条件
> 只有当该宠物是一个奇遇宠物时，才显示底部的触发记录模块。
> 
> * [x]  已完成

没有必要

**Comment by Kaviilee** [comment]
> ## 游戏内宠物密鉴跳转
> 以下为流年反馈
> 
> 在游戏内点击宠物图标，想知道怎么获取到这个宠物，但是跳转的成就是错误的
> 
> 如下 ![image](https://user-images.githubusercontent.com/8476969/151191810-33988d8e-9084-4b67-b7aa-1a5cc5c1b794.png)
> 
> 点击以后跳转到的是成就【命中注定】召唤一次土土 ![image](https://user-images.githubusercontent.com/8476969/151191826-fab6e9f8-c667-4bc7-8dd7-d5b0ee686b6a.png)
> 
> 而正常的需求是怎么获取到，应该跳到如果获取这个宠物 ![image](https://user-images.githubusercontent.com/8476969/151191849-b70a4125-0a11-4f82-824f-ebfcc3519016.png)
> 
> https://github.com/JX3BOX/game 得让游戏内的宠物打开后，要么打开奇遇攻略，要么打开物品攻略。
> 
> * [x]  已完成

通过成就攻略组完善在攻略里
