### ISSUE TITLE
【技艺助手】前端开发一期

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#23]
# 文件
前端入口文件位置：views/price/Cooking.vue
模块写在components/cooking/xxx
样式写在assets/css/cooking/xxx.less
访问入口  /cooking

## 数据
！！！所有接口请求后，应缓存在sessionStorage!!!

## 图片
![image](https://user-images.githubusercontent.com/8476969/153740749-80d7ff47-3b62-4e86-80e2-6396c394b8b7.png)
文件位置：https://github.com/JX3BOX/jx3box-oss 库下的image/cooking目录
访问地址使用
```js
import {__imgPath} from '@jx3box/jx3box-common/data/jx3box.json
__imgPath + 'image/cooking/xxx.png'
```

## 图标
图标资源文件位置 https://github.com/JX3BOX/jx3-icon 库下的icon目录
访问地址使用
```js
import {__iconLink} from '@jx3box/jx3box-common/js/utils.js
__iconLink(icon_id)
```

**Comment by iRuxu** [comment]
# 头部
![image](https://user-images.githubusercontent.com/8476969/153705044-9db0eb91-6142-4e35-bddf-d319274f4c8c.png)

## 1. 标题
标题内容：技艺助手
具体样式等我来改

## 2.左：TAB
正式服4/怀旧服5种类型，对应表名
烹饪：cooking
锻造：founding
梓匠：furniture（仅正式服）
制药：medicine
缝纫：tailoring

每个TAB名字前面使用一个图标，要有active状态

## 3.右：服务器选择框
物价参考使用的【服务器】下拉选择服务器

原始数据：
https://github.com/JX3BOX/jx3box-data/blob/master/data/server/server_std.json
https://github.com/JX3BOX/jx3box-data/blob/master/data/server/server_origin.json

```js
import servers_std from '@jx3box/jx3box-data/data/server/server_std.json
```

**Comment by iRuxu** [comment]
# 左侧边栏
![image](https://user-images.githubusercontent.com/8476969/153705178-260dc146-3b6c-4272-9803-2f1fd7e7474e.png)

## 获取技艺某种类型的列表
GET ~~/manufactures/{type}~~ /manufactures

#### URL Path Params:
~~- type: 技艺类型  cooking funding furniture medicine tailoring~~

#### URL Query Params:
- ids: 可选，批量查询产物Id集合，1,2,3
- mode: 可选，模式，simple 时，接口只返回 'ID', 'Name', 'IconID', 'nLevel', 'Quality' 字段
- name: 可选，按名称模糊搜索
- client: 可选，客户端类型 std|origin
- type: 可选，技艺类型  cooking funding furniture medicine tailoring

#### 接口使用示例
```js
import {$node} from '@jx3box/jx3box-common/js/https'
$node().get('/manufactures?type=cooking',{
    params : {
        client : std|origin,
        mode : 'simple'
    }
}).then((res)=>{
    
})
```

## 样式
整体高度可使用calc 100vh - @bread-height - @header-height -xx，不要像游戏里那么小
需要展示图标+名字，还有品质颜色框（2绿3蓝4紫5橙）
可以使用jx3box-editor库下的Item组件显示浮窗
```js
import Item from '@jx3box/jx3box-editor/src/Item.vue'
```
专精的要显示 专精图标

## 搜索框
前端本地v-show过滤控制

## 购物车
后面有个输入框和+号，代表加入购物车
鼠标hover在对应行才显示添加购物车控件
注意最多只能有20种加入购物车，之后就要禁用掉，在顶部可以有个(0/20)来提醒已经有多少加入购物车

**Comment by iRuxu** [comment]
# 中央区域
![image](https://user-images.githubusercontent.com/8476969/153707402-e78e9a52-370a-4963-98b2-fd04e005c446.png)

## 样式
使用对应的图片美化，例如添加边框等，见图片文件夹。

## 字段解析
field|desc
---|---
ID|物品id
Name|物品名称
nLevel|需求等级
NeedExpertise|需要专精
szTip|配方来源
ProfessionID|职业: 4烹饪,7医术
---|---
requireItemArr|制造需要物品数组
RequireItemType|需要物品类型
RequireItemIndex|需要物品id对应other表，other表的UIID是描述的id，对应item.txt表
RequireItemCount|需要物品数量
CostVigor|消耗精力
---|---
Exp|获得经验值
xx|获得数量

更多细节 ：
[小吃小药.zip](https://github.com/JX3BOX/pvx/files/8053204/default.zip)

## 显示字段
包括所有有意义的字段，经验值等等
成品与每个元素物品下面显示近期价格
同时显示所有材料的总价格 + 所需精力
*其中材料总价格需要同时判断可能是交易行价格 或 自己原产价格（例如肉馅）

## 接口


### 1.获取技艺某种类型的单项详情 @Kaviilee 
GET /manufacture/{type}/{id}

#### URL Path Params:
- type: 技艺类型  cooking funding furniture medicine tailoring
- id

#### URL Query Params:
- client: 可选，客户端类型 std|origin

### 2.获取技艺某种类型的单项详情

GET /manufacture/{type}

#### URL Path Params:
- type: 技艺类型  cooking founding furniture medicine tailoring

#### URL Query Params:
- client: 可选，客户端类型 std|origin
- ItemID, 可选，物品id

### 3.根据ids获取物品的详情

GET /other

#### URL Query Params

- ids: 可选，批量查询物品，ids=1,2,3
- client: 可选，客户端类型 std|origin，默认为 std

### 4. 获取craft_belong.json

```js
import { __iconPath } from "@jx3box/jx3box-common/data/jx3box.json";
import axios from 'axios';

const getCraftJson = () => {
    return axios.get(__iconPath + "pvx/cooking/output/craft_belong.json");
}
```

### 5.根据ids或者name获取价格

GET /craft/price

#### URL Query Params

- ids: 可选，批量查询物品，ids=1,2,3
- name: 可选，原料名称
- client: 可选，客户端类型 std|origin，默认为 std

### 2.交易行价格 @blankqwq

**Comment by iRuxu** [comment]
# 右侧边栏
![image](https://user-images.githubusercontent.com/8476969/153707455-3bab9b9c-de18-4694-a80a-937fff7d83e1.png)
右侧购物车模块，见上图。

## 头部
导入物品清单，下拉列表
### 接口 @blankqwq


## 上部分
全部被加入购物车的物品列表，单行含数量展示，已经x删除按钮
最后有一个总价格（交易行）

## 中部分
全部被加入购物车的物品的原料计算
含数量展示

### 接口 @Kaviilee 



## 底部
保存至物品清单，点击弹出对话框保存一个清单名字

### 接口 @blankqwq

**Comment by iRuxu** [comment]
## 价格接口
https://helper.jx3box.com/api/item_groups/with_price?server=%E8%9D%B6%E6%81%8B%E8%8A%B1&keys[]=index1&keys[]=index2&keys[]=teshucailiao

**Comment by iRuxu** [comment]
## 获取某种技艺产出列表（左侧边栏）

**Comment by iRuxu** [comment]
## 获取某个产品的原料

**Comment by iRuxu** [comment]
## 物品清单

最后还有一个【保存清单】按钮，生成一个物品清单，
加载清单

**Comment by iRuxu** [comment]
## 商店价格说明
![9GA{2QKJ)~PKJXJM WD0JZX](https://user-images.githubusercontent.com/8476969/153740340-b7b9971a-c830-4630-be36-ad2dd3744cc9.png)
![NDKA~4`A_7PL0{$F66CZJDM](https://user-images.githubusercontent.com/8476969/153740342-ee6b712e-de6a-40ce-a09a-4406f51e2c12.png)
紫色是other表ID，蓝色是价格，个位十位是铜，百位千位是银，以此类推
可以使用公共GamePrice组件显示价格

```js
import GamePrice from '@jx3box/jx3box-common-ui/src/wiki/GamePrice.vue
<GamePrice price="xxx" />
```

**Comment by qaz528093426** [comment]
前端功能完成： 物品列表展示 购物车列表展示已完成 所需材料的添加以及移除在开发中，加入购物车 、搜搜物品 、移除购物车、切换类型已经完成，样式待优化，待联调数据接口

**Comment by iRuxu** [comment]
## 批量获取物品金价
###### URL
> {{helperDomain}}/api/items/price
###### HTTP请求方式
> GET
###### 请求参数
|字段名称|字段类型| 是否必须 |说明                              |
|:-----   |:------ |:------|:-----------  |
|list  |string|Y   |  例如：10_101,10_103|
|server | string |Y| 服务器名，例如:乾坤一掷|

###### 返回字段
|返回字段|字段类型|说明                              |
|:-----   |:------|:-----------------------------   |
|code   |int    |返回结果状态   |
|data  | array | 更新后的成就列表|
|message |string |消息                         |
###### 返回示例
成功
```json
{
    "code": 200,
    "data": {
        "10_101": {
            "item_id": "10_101",
            "avg_price": 478963
        }
    },
    "message": "昨日平均价格"
}
```

失败
```json
{
    "code": 400,
    "message": "参数错误，不能为空"
}
```

**Comment by qaz528093426** [comment]
技艺助手功能基本开发完成已经提交pr
目前遇到问题
前端：
关于怀旧服正式服的sessionStorage参数未找到
物品类别 craftbelongname.txt 文件需要转json还不清楚放在哪个库里面
接口问题：
物品列表接口需要返回当前版本这一类型中的全部物品
价格查询接口目前查不到价格
