### ISSUE TITLE
坐骑大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#29]
# 简介
~~类似奇遇大全，宠物大全那样，做一个列表+详情页。~~

~~其中前端的一些属性展示见word，具体可以问南宫伯。~~

~~另外一个excel是一个玩家自制的，我们可以从中找一些灵感。~~

~~另外之前有人提议过，在详情页，同时展示这个马在交易行的价格，这个主意很好，具体接口要找blank要，其实和物品百科的详情是同一个接口，不过他最近要优化。~~

[坐骑.zip](https://github.com/JX3BOX/pvx/files/8629280/default.zip)

**Comment by iRuxu** [comment]
# 属性展示
1. 交易行价格

**Comment by iRuxu** [comment]
## 入口
<img width="417" alt="image" src="https://user-images.githubusercontent.com/8476969/215722201-7607eb63-8eba-4185-a36a-c8a147b5aa15.png">

应用标识 horse

- [ ] 已完成

**Comment by iRuxu** [comment]
## 列表页

### 抬头
<img width="834" alt="image" src="https://user-images.githubusercontent.com/8476969/215722508-3189de23-63e2-4846-9033-b95e5adb1d29.png">
这个地方 要和宠物奇遇保持一致，@saxa 加一个坐骑大全的，然后这次同时解决一下 4k高清问题。
联系设计胧月

### 列表
整个图片资源由南宫伯负责，样式和产品确认
img-homeland\homeland\std\data\source\home\furniture\mount   对应线上地址
https://img.jx3box.com/homeland/homeland/std

### 接口
接口联系 不咕提供

- [ ] 已完成

**Comment by iRuxu** [comment]
## 详情页（单页）
参考宠物，
对应物品id，获取物品攻略展示逻辑基本照搬（但需要自己去理解一下）

额外存在一个特殊模块，就是列出同名坐骑（因为有些马存在不同方向属性）

- [ ] 已完成

**Comment by x3zvawq** [comment]
【接口文档】
baseurl: https://node.jx3box.com
methods: GET

**Comment by x3zvawq** [comment]
【列表】
url: /horses
query: 

|参数|类型|说明|示例|默认值|
|---|---|---|---|---|
|client|string|客户端|origin |std|
|page|number|页码|20|1|
|pageSize|number|每页大小，最大50|20|15|
|-|-|-|-|-|
|keyword|string|关键词，返回名字里包含给定关键词的马匹/马具|里飞沙|-|
|speed|number|移动速度，返回移动速度大于给定值的马匹|110|-|
|attr|string|特性，返回包含指定特性的马匹，有哪些特性可以通过`horse/attrs`查询，传入特性的name，需要注意的是双骑和渡水好像不在attrs，可以传`双骑`/`渡水`来过滤这样的坐骑|双骑||
|feed|string|喂食方式，返回用指定方式喂食的马匹，可以通过`horse/feeds`查询，需要前端做好过滤，因为feeds这个表很阴间，多个feed用逗号分隔|2,3,4|-|
|type|number|查询类型，0=普通坐骑，1=奇趣坐骑，2=马具|1|-|
|-|-|-|-|-|
|ids|string|查找多个指定id的数据时使用，传入该参数会改变返回格式！|8_114514,8_1919810||

**Comment by x3zvawq** [comment]
【单个数据查询】
url: /horse
query:

|参数|类型|说明|示例|默认值|
|---|---|---|---|---|
|client|string|客户端|origin |std|
|id|string|坐骑/马具ID|8_114514|-|
|type|number|传入2查询马具|2|-|

**Comment by x3zvawq** [comment]
【坐骑属性】/【坐骑喂食方式】
url: `/horse/attrs` `/horse/feeds`
没有参数
