### ISSUE TITLE
宠物大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#3]
## 前端文件位置
模板：/src/pages/pet目录
样式：/src/assets/pet目录
api：/src/service/pet.js

## 静态资源库
https://github.com/JX3BOX/jx3-pvx/tree/master/pet
对应线上地址 icon.jx3box.com/pvx/pet/

### 宠物福缘文件
icon.jx3box.com/pvx/pet/output/pet_lucky.json

### 宠物分数文件
~~icon.jx3box.com/pvx/pet/output/pet_score.json~~

**Comment by iRuxu** [comment]
## 列表页
展示为卡牌，分页，福缘靠前。
同时显示通宝价格。
支持多种筛选

## 详情页
模块1：宠物基本信息
模块2：宠物地图
模块3：宠物攻略（来自成就百科/物品百科）

**Comment by iRuxu** [comment]
## 接口列表

#### `/pets` 宠物列表接口

Demo:
`http://node.jx3box.com/pets?Name=灰&client=origin`

```
URL: http://node.jx3box.com/pets

URL Query params:

   client: 可选，std,origin 默认为std

    Name: 可选，模糊搜索宠物名

    Star: 可选，宠物星级

    Quality: 可选，宠物品质

    per: 可选，每页条数

    page: 可选，页码

    ids: 可选，批量查询宠物 ids=1,2,3

    Class： 可选，宠物种类，当为空时返回所有种类，注意：Class=0 不生效
    
    Source： 可选，获取途径，当为空时返回所有途径，注意：Source=0 不生效
```

#### `/pet/:id` 宠物详情接口

Demo:
`http://node.jx3box.com/pet/200`

```
URL: http://node.jx3box.com/pet/{id}

URL Path params

    client: 可选，std,origin 默认为std

    id: 宠物id
```

#### `/pet/:id/skill`  宠物技能接口
Demo: 
`http://node.jx3box.com/pet/200/skill`

```
URL: http://node.jx3box.com/pet/{id}/skill

URL Path Params

    client: 可选，std,origin 默认为std

    id: 宠物id
```
![image](https://user-images.githubusercontent.com/25825282/150638549-cd49443a-c3b7-4a04-9a5d-b599c23d7088.png)

`http://node.jx3box.com/skills?ids=1,2,3` 然后根据level拿出来

#### `/shop` 商城价格接口

Demo:
`http://node.jx3box.com/shop?ID=3134&client=origin`

```
URL: http://node.jx3box.com/shop

URL Query params:

    ID: 可选，商城物品ID
    client: 可选，std,origin 默认为std
    itemType: 可选，物品类型
    itemId: 可选，物品id
```

**Comment by nierssaxa** [comment]
![F1N){ F}ZZUA}DRST82CX8D](https://user-images.githubusercontent.com/97571785/150111205-b6d67c7a-6dee-430d-a3b1-4198f155aa0c.png)
1.横间距30px
2.竖间距30px
3.按照游戏内获取方式分类筛选，可以视情况缩短搜索框
4.福源宠物位置，福源宠物默认置顶
5.一排显示3~4个

**Comment by nierssaxa** [comment]
![7 2398HG5P{Z2M TK6T99NO](https://user-images.githubusercontent.com/97571785/150111586-d6cc18a4-1e3f-442e-b426-8672dd12a0b8.png)
1~5：模块A
1.宠物技能，鼠标移上去小浮窗展示宠物技能说明
2.宠物类型，获取途径
3.用实心五角星代替数字星级展示
4.宠物说明（游戏内黄字）
5.获取线索

6：模块B
6.新增倒三角表示可以展开

7：模块C
7.攻略流程

**Comment by nierssaxa** [comment]
![SNUTJ}L%F_3Q(P8A6PF W7S](https://user-images.githubusercontent.com/97571785/150112074-bbe03fbb-71a4-4f8c-b22d-5777ab41ec64.png)
1.正三角表示可以折叠
2.宠物地图
3.触发方式
4.区服选择
5.触发记录
注：345可以和2左右互换，更换后效果可能好一点

**Comment by nierssaxa** [comment]
https://app.mockplus.cn/s/Ziy608250g_9

设计稿、切图地址（7天有效）

**Comment by nierssaxa** [comment]
尽可能边角平滑（圆角），视觉上有轻便丝滑的感受

**Comment by TYguigui** [comment]
游戏中宠物的筛选方法为：

- 通过种类搜索  type
- 通过获取途径搜索  source

所以宠物列表接口可能需要修改一部分：

- 增加type和source这两个params以适应游戏的筛选模式
- 返回的结果中最好能增加一项宠物分数score，用于复刻游戏中的展示卡片

整理并验证好的相关JSON如下
`[{
        "type": 0,
        "name": "所有种类"
    },
    {
        "type": 1,
        "name": "水族"
    },
    {
        "type": 2,
        "name": "走兽"
    },
    {
        "type": 3,
        "name": "禽鸟"
    },
    {
        "type": 4,
        "name": "机关"
    }
]`
`[{
        "source": 0,
        "name": "所有途径"
    },
    {
        "source": 5,
        "name": "世界奇遇"
    },
    {
        "source": 6,
        "name": "积分回馈"
    },
    {
        "source": 7,
        "name": "秘境奇遇"
    },
    {
        "source": 8,
        "name": "门派特有"
    },
    {
        "source": 9,
        "name": "游戏活动"
    },
    {
        "source": 10,
        "name": "限时宠物"
    },
    {
        "source": 11,
        "name": "运营活动"
    }
]`

**Comment by Kaviilee** [comment]
> 游戏中宠物的筛选方法为：
> 
> * 通过种类搜索  type
> * 通过获取途径搜索  source
> 
> 所以宠物列表接口可能需要修改一部分：
> 
> * 增加type和source这两个params以适应游戏的筛选模式
> * 返回的结果中最好能增加一项宠物分数score，用于复刻游戏中的展示卡片
> 
> 整理并验证好的相关JSON如下 `[{ "type": 0, "name": "所有种类" }, { "type": 1, "name": "水族" }, { "type": 2, "name": "走兽" }, { "type": 3, "name": "禽鸟" }, { "type": 4, "name": "机关" } ]` `[{ "source": 0, "name": "所有途径" }, { "source": 5, "name": "世界奇遇" }, { "source": 6, "name": "积分回馈" }, { "source": 7, "name": "秘境奇遇" }, { "source": 8, "name": "门派特有" }, { "source": 9, "name": "游戏活动" }, { "source": 10, "name": "限时宠物" }, { "source": 11, "name": "运营活动" } ]`

接口新增 `Class 种类`，当 `Class` 为空时，返回所有种类；`Source 获取途径` 当 `Source` 为空时，返回所有途径。新增宠物分数Score字段

**Comment by TYguigui** [comment]
个别宠物的图片缺失，已经联系南宫伯补全，需要同步一下gitee仓库的内容
技能接口调不出宠物id>241的宠物技能
比如幽明录（id:336）技能接口没有返回结果 https://node.jx3box.com/pet/336/skill

**Comment by Kaviilee** [comment]
> 个别宠物的图片缺失，已经联系南宫伯补全，需要同步一下gitee仓库的内容 技能接口调不出宠物id>241的宠物技能 比如幽明录（id:336）技能接口没有返回结果 https://node.jx3box.com/pet/336/skill

获取成就攻略和宠物技能改用苦瓜的接口，`https://helper.jx3box.com/api/wiki/post?type=item&source_id=8_5879&supply=1`, `source_id` 为宠物详情内的 `{ItemTabType}_{ItemTabIndex}`
