### ISSUE TITLE
家具大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#5]
# 背景
## 资源
图片资源：https://gitee.com/JX3BOX/jx3-pvx/furniture
原始数据：https://gitee.com/JX3BOX/jx3-pvx/house/raw

## 前端
旧版的前端文件位置：https://github.com/JX3BOX/app/tree/master/src/core/furniture
新版的目录在本项目 /pages/house/furniture.vue，注意拆分多个模块
线上访问路径：https://www.jx3box.com/pvx/furniture/

**Comment by TYguigui** [comment]
1.旧版家具前端（https://github.com/JX3BOX/app/tree/master/src/core/furniture）
调用的家具接口好像是“胖叔叔”的失效接口，可能需要新的接口
2.gitee仓库中的jx3box-oss中有图片资源更新 img.jx3box.com未同步
