### ISSUE TITLE
捏脸单页

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#70]
## 顶部
<img width="647" alt="image" src="https://user-images.githubusercontent.com/8476969/190326341-4d035d00-004d-41ce-82a2-b376c7469983.png">

1. 保留搜索栏，搜索后回车或点击右侧按钮，跳到列表页，并展示搜索结果。
2. 左侧的发布改为【返回列表】

- [x] 已完成

**Comment by iRuxu** [comment]
## 头部
### 接口
@flyflyknife 查看单个捏脸作品
https://github.com/JX3BOX/jx3box-api/blob/master/DOCS/%E6%8D%8F%E8%84%B8.md


### 海报
先展示海报 banner 字段，居中，背景色填充 `@color`，6px圆角。
当没有时，则隐藏。

### 基本信息
参考配装器风格：
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/8476969/190327968-37d37297-614e-455c-b0d3-5dd8eb80f281.png">
1. 标题
2. 头像+昵称（具体由是否原创决定，显示原创作者，或者当前作者，需要加链接）
3. 更新时间
4. 客户端版本、体型（体型弄成和客户端类似的tag形式，蓝男女紫正太绿萝莉粉）
5. 精选情况
6. 描述（remark），没有不显示

- [x] UI已完成
- [x] 接口已完成

**Comment by iRuxu** [comment]
## 右上角op操作插槽
参考配装器，增加下架/上架，精选/取消精选
<img width="250" alt="image" src="https://user-images.githubusercontent.com/8476969/190328122-774d797e-553a-4b58-ad8e-1025555be262.png">

### 管理员设置精华

group >= 128

```
PUT /face/:id/manager/set/star
Path Params:
    id 捏脸主键
Response:
    {
        code:0,
        Msg:"操作成功"
    }
```

### 管理员取消精华

group >= 128

```
PUT /face/:id/manager/cancel/star
Path Params:
    id 捏脸主键
Response:
    {
        code:0,
        Msg:"操作成功"
    }
```

------

### 管理员上线线一个捏脸数据

group >= 128

```
PUT /face/:id/manager/online
Path Params:
    id 捏脸主键
Response:
    {
        code:0,
        Msg:"操作成功"
    }
```

### 管理员下线一个捏脸数据

group >= 128

```
PUT /face/:id/manager/offline
Path Params:
    id 捏脸主键
Response:
    {
        code:0,
        Msg:"操作成功"
    }
```

- [ ] 已完成

**Comment by iRuxu** [comment]
## 预览区
暂时使用原来的形式，展示Images字段

## 购买区
如果是免费，则显示是免费。
如果是付费，则要显示价格，并且增加购买按钮。

购买接口： @flyflyknife 

- [x] UI已完成
- [x] 接口已完成

https://github.com/JX3BOX/jx3box-api/issues/184#issuecomment-1250085443

**Comment by iRuxu** [comment]
## 下载区
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/8476969/190336467-985f2cdd-2b37-478a-8f1f-928166bd1e3c.png">

额外在下载下面新增附件列表。
其中最新的应该靠前，应该倒序。

注意此模块，应该要用户已经购买了本脸型才可以请求出来。
所以应该要额外有一个接口判断用户是否已经购买了该作品。  @flyflyknife 

显示一段话
```
如数据中包含付费元素，将不可用于新建角色导入，如用于新建角色请点击最下方导出
```


### 获取附件列表

```
GET   /api/charge_attachment/{postType}/{postId}
Path Params:
    
    postType 文章类型
    postId 文章id

    include_deleted {int} 0 或 1， 0 默认值，不包含用户已删除的附件，1 包含用户已删除的附件

Query Params:
    
    pageIndex, pageSize 分页参数

Response:

{
    "code": 0,
    "msg": "ok",
    "data": {
        "has_buy": true, //是否已经购买该篇文章的附件
        "list": [ // 如果has_buy为false该list为空
            {
                "id": 16,
                "uuid": "f01016f763514016bae9678ce7258547", // 唯一表示
                "user_id": 8, // 作者id
                "describe": "xxx", // 附件描述
                "download_count": 0, //下载次数
                "created_at": "2022-01-01 00:00:00", //创建时间
                "has_deleted": false, // 是否被作者删除 【由于需要提供被删的给用户下载因此保留该条记录，可以通过查询查询排除该条记录】
                "post_type": "test",
                "post_id": "1"
            },
            ....
        ],
        "page": {
            "index": 1,
            "pageSize": 15,
            "total": 3,
            "pageTotal": 1
        }
    }
}
```

### 获取最新的一个附件

没有被作者或者管理删除的最新一个版本

```
GET   /api/charge_attachment/{postType}/{postId}/lastest
Path Params:
    
    postType 文章类型
    postId 文章id

Query Params:
    
    pageIndex, pageSize 分页参数

Response:

    {
        code: 0
        data: {
            "has_buy": true, //是否购买，已购买的话
            "record": { // has_buy为false时，该数据为空
                id: xxx,
                ....
            }
        }
    }
```

### 获取附件下载地址

```
GET "/api/charge_attachment/download/{postType}/{postId}/{uuid}"
Path Params:
    postType {strign} 文章类型 可以从附件列表的单个元素中获取
    postId {int} 文章id 可以从附件列表的单个元素中获取
    uuid {string} uuid 可以从附件列表的单个元素中获取
Response:

    {
        code: 0, //非零表示没有权限下载，里面时错误代码
        data: {
            url:"xxx",//文件下载地址 ，获取到该值后，可以通过 window.open(url)打开新窗口来下载
        }
    }
```

### 获取下载历史 

当文章被删除后，或者附件被删除后,曾经下载过的数据，可以通过这个接口查询重新下载

```
GET /api/charge_attachment/download-history
Query Params :
    通用分页参数：pageIndex， pageSize
Response：

{
    "code": 0,
    "msg": "",
    "data": {
        "list": [
            {
                "id": 1,
                "uuid": "cf84d769d34f4a7da3a5706db1db72c9",
                "user_id": 8,
                "post_type": "face",
                "post_id": 22,
                "created_at": ""
            }
        ],
        "page": {
            "index": 1,
            "pageSize": 15,
            "total": 1,
            "pageTotal": 1
        }
    }
}
```

**Comment by iRuxu** [comment]
## 数据区

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8476969/190337250-067e86f8-146e-411e-9cb8-69fb77954797.png">

和以前一样。但是如果用户没有购买过，是看不到这个字段的（data）。 @flyflyknife 
但是这里的贴花这次不要静态引入一个json了。
本次直接用axios的形式请求线上的贴花文件。做到这里跟你说

- [ ] UI已完成
- [x] 接口已完成

**Comment by iRuxu** [comment]
## 作者的其他作品

随机显示指定作者的若干个作品。
只需要返回id, images，title，body_type，client 字段。
支持user_id,client,body_type 查询参数。
@flyflyknife 


- [x] 已完成

-----------------------------


### 获取随机捏脸


```
GET /api/face/random
URL Query Params:  // 以下查下字段均为可选， 不传字段表示忽略该字段筛选

   
    "user_id": 1, 可选
    "body_type": 1 // 体型 可选
    "client":"origin", // 客户端类型 可选
    "star": 1 //是否精选
    
    "limit": int // 返回捏脸的个数 可选，不填默认为3

Response:

    {
        code:0,
        data:{
            list: [
               {
                "id":1,
                "images":[],
                "title":"xx",
                "body_type":"",
                "client": ""
               }
            ]
        }
    }
```

**Comment by iRuxu** [comment]
## 交互区

常规打赏组件与评论。
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/8476969/190337797-18993d24-ff2b-405b-953f-c54d02951284.png">

评论需要新增对应作者关联、短消息等，请 @flyflyknife 注意。

- [ ] 已完成

**Comment by flyflyknife** [comment]
> ## 交互区
> 
> 常规打赏组件与评论。 <img alt="image" width="1463" src="https://user-images.githubusercontent.com/8476969/190337797-18993d24-ff2b-405b-953f-c54d02951284.png">
> 
> 评论需要新增对应作者关联、短消息等，请 @flyflyknife 注意。
> 
>     * [ ]  已完成

这个需求没明白 @iRuxu

**Comment by iRuxu** [comment]
新UI
<img width="841" alt="image" src="https://user-images.githubusercontent.com/8476969/191081162-16344dfa-b053-4e2b-a809-e0fad6bf5839.png">
