### ISSUE TITLE
捏脸项目优化Step1

### ISSUE THREAD

**Issue by nierssaxa** [JX3BOX/pvx_v1#79]
### 新增Banner
![JB}IOAMLL%S02`ET1WD5O4Q](https://user-images.githubusercontent.com/97571785/208320872-4430654e-4f29-4326-ba3a-68737f9763e2.png)
![A2R{BEJ W)PF_KPC$)44YMR](https://user-images.githubusercontent.com/97571785/208320929-e0674fdb-0093-4166-8875-766def34f2f3.png)

在关键词搜索上方新增一个banner，尺寸走主页。
OS端可能需要新增一个捏脸的接口

**Comment by iRuxu** [comment]
## 增加海报

在现有首页 /banner/v2的接口上，新增过滤到source_type=face的条目。
并在捏脸列表页增加对应slider

- [ ] 已完成

**Comment by iRuxu** [comment]
## 单页优化
<img width="319" alt="image" src="https://user-images.githubusercontent.com/8476969/216758699-d015c27e-0ff2-4e01-b180-853cda86f2b2.png">
这里设计师原意应该不是弄成这样，具体联系胧月

- [ ] 已完成

**Comment by nierssaxa** [comment]
> ## 增加海报
> 在现有首页 /banner/v2的接口上，新增过滤到source_type=face的条目。 并在捏脸列表页增加对应slider
> 
> * [x]  已完成

样式修改，不再新增传统banner，转而用编辑推荐。
暂定6个位置，放置捏脸海报。
海报操作逻辑大致为，【设计制作捏脸海报】→【上传到主页banner】→【点击一个新增的按钮A】→【复制这条海报的信息到捏脸的海报列表】→【列表收到信息新增第7个海报】→【隐藏原先第1个海报】

![1675704008384](https://user-images.githubusercontent.com/97571785/217040230-04c887a2-5213-4aab-8165-bfccf39b7bb1.png)

**Comment by nierssaxa** [comment]
> ### 新增Banner
> ![JB}IOAMLL%S02`ET1WD5O4Q](https://user-images.githubusercontent.com/97571785/208320872-4430654e-4f29-4326-ba3a-68737f9763e2.png) ![A2R{BEJ W)PF_KPC$)44YMR](https://user-images.githubusercontent.com/97571785/208320929-e0674fdb-0093-4166-8875-766def34f2f3.png)
> 
> 在关键词搜索上方新增一个banner，尺寸走主页。 OS端可能需要新增一个捏脸的接口

要求废弃。
新界面样式与小程序匹配。
https://www.figma.com/file/O5450TSGCIf9aEvp3mojdo/JX3BOX-PVX?node-id=1%3A2&t=KNDRyHJF59FWL0dA-1

**Comment by Kaviilee** [comment]
## 最新新闻列表
`/api/cms/news2` 新增query参数 source_type，用于查询对应source_type的头条

**Comment by yu-minggang** [comment]
1920*1080
编辑推荐9个   一屏3个半
脸型14个 一屏7个半
2560
3840
