### ISSUE TITLE
声望大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#84]
## 边距问题
<img width="638" alt="image" src="https://user-images.githubusercontent.com/8476969/222511216-fb9d94fd-3b07-4d6b-ba6a-205230221542.png">
<img width="739" alt="image" src="https://user-images.githubusercontent.com/8476969/222511261-2b792134-dce5-4927-a05d-8a53bae7beed.png">
边距和其他不一致

- [x] 已完成

**Comment by iRuxu** [comment]
## 锦旗大全
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/8476969/222512220-cecd4975-f762-4776-99cb-5582ac72f88c.png">

缺失的锦旗问题，看看南宫伯那边怎么说
有可能是图片大小写的问题

- [x] 已完成

**Comment by iRuxu** [comment]
## 一些无效的声望隐藏
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/8476969/222511932-5613005e-27e1-4b3d-8cbc-732d7c50f62a.png">
<img width="816" alt="image" src="https://user-images.githubusercontent.com/8476969/222511865-fd2a27ea-cada-497a-9351-8e0c650da6ac.png">

- [x] 已完成

**Comment by nierssaxa** [comment]
## 地图组件
<img width="537" alt="image" src="https://user-images.githubusercontent.com/8476969/222512415-c0929291-8562-4235-b749-12e0c2d9e159.png">

按之前计划，改进jx3box-map库？
这个地图组件在这里缩小了，坐标标点不正确了，要在修正图片大小时，修正坐标位置？

- [ ] 已完成

**Comment by iRuxu** [comment]
## 路由修正

<img width="565" alt="image" src="https://user-images.githubusercontent.com/8476969/222512997-d4aa0e44-c4ef-431e-840f-9cf3aa3a1be8.png">

单页直接就是 /reputation/:id

所有的pvx类型里，都是这种模式

- [x] 已完成

**Comment by iRuxu** [comment]
## 资料片新增修改
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/8476969/222513847-5386b7ce-20f6-4e8a-b187-3a938241e07a.png">

这个地方换成人工维护，通过引用 https://github.com/JX3BOX/jx3box-common/blob/master/js/api_misc.js 中的 `getBreadcrumb('reputation-newest')` 会得到一个列表
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/8476969/222514019-6ba15bfa-2810-4136-86db-9c515e6271ed.png">

自己split成数组，再展示对应的声望即可

- [x] 已完成

**Comment by nierssaxa** [comment]
评论区域，应当用白底圆角，上下左右边距20

**Comment by nierssaxa** [comment]
## 搜索优化
搜索结果返回的时候，应当依旧以版本分类的形势展现搜索结果。比如搜索平，则第一行显示资料片新增以及下面的有平字的声望。如果没有则不显示（包括资料片新增这个分类标题）。具体可以参考 【全部】的捏脸分类下搜索的返回。

前端通过v-show来控制

- [x] 已完成

**Comment by iRuxu** [comment]
## 声望成就ID获取

接口：https://data.jx3box.com/pvx/reputation/output/reputation_link_achievement.json
匹配正确的成就id

（关联的：https://github.com/JX3BOX/jx3-pvx/issues/3  由踏池在做）

- [x] 已完成

**Comment by fifthThirteen** [comment]
> 

szIconPath 没有

**Comment by iRuxu** [comment]
## 无效声望隐藏问题

当bHide=1时，该声望隐藏

- [x] 已完成
