### ISSUE TITLE
书籍大全

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#85]
## 原型图
https://www.figma.com/file/O5450TSGCIf9aEvp3mojdo/JX3BOX-PVX?node-id=341%3A7787&t=BqoxvdKB37rpt6pg-1

**Comment by iRuxu** [comment]
## 功能说明
最近阅读，本地建一个localstorage的key
`book_readings:1,2,3,4` 最多记录最近的20条

**Comment by nierssaxa** [comment]
### 全部页面改动
1.第一行为最近阅读，去掉全部（如果没有最近阅读的数据，则隐藏）
2.顺序为杂集→佛学→道学（与顶部顺序一致）
3.道学底色改为#194372 (25,67,114),新颜色的切片已发群
4.每行不再做左右滑动(切换)，一次性读取16个该分类最新的书籍数据，根据浏览器宽度计算展示，最少为8个
5.鼠标移入书籍时，对书籍做一个阴影（书籍那张图片，不包含下面的白色描述框），阴影数据如下
box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.8);
对应为X轴0，Y轴0，blur10，颜色#000000，透明度80%

![VCF MA~IDMIIYU7E$MYM42U](https://user-images.githubusercontent.com/97571785/224463471-4cb4b020-d25b-4349-b86f-39001e5b998e.png)

**Comment by nierssaxa** [comment]
### 内页注意要点
1.套书请求时，一次性将套书请求完，并根据浏览器宽度计算展示，不足时换行，每行之间的间隔为20

**Comment by nierssaxa** [comment]
### 内页优化
1.此处应当水平对齐，即所需材料几个字应当在红线上
![Z)1ARN3A~$6CV(RE 8MP~33](https://user-images.githubusercontent.com/97571785/224515845-9b0a8104-a6f0-4c7a-96d9-d20b6a52d24d.png)

2.两处取消加粗，内容的标题从14px放大到16px（内容的标题不取消加粗）
![@XR RP`K7_2PGQAMM$VI39O](https://user-images.githubusercontent.com/97571785/224515924-a0561fc7-0dfb-4c08-9764-0550490a13d7.png)

3.继续和返回按钮不再使用文字，做成20x20的底框+白色的箭头，箭头注意调整尺寸为双数（注意边距依旧是10）
![SD0{($J97Z9ANK(I{WOVSUA](https://user-images.githubusercontent.com/97571785/224516119-47eead50-02b9-436b-998c-6fc966b70083.png)

4.套书标题处，修改为套书 · 套书的名字
如https://www.jx3box.com/book/366_4
晟江杂记 → 套书 · 晟江杂记

5.移除常态碑铭展示，当书籍来源为碑铭时，在碑铭后面加上蓝色带下划线14px的文字“查看位置”，用户点击后，在浏览器中间弹出浮窗，展示碑铭。（注意浮窗弹出后，加上40%透明黑色背景）
![8MG% CB(F P M{WL`}JS(43](https://user-images.githubusercontent.com/97571785/224516750-fc37e42c-1500-442a-b3d8-ea0f2f42ee29.png)

**Comment by iRuxu** [comment]
thx组件  和  评论，不能受有没有攻略影响，始终得展示
可能需要去改common-ui的公共组件

- [x] 已完成

**Comment by iRuxu** [comment]
其次：看看碑铭要不要做？踏池那边是可以拿到所有碑铭坐标，然后调用不咕的那个地图组件显示碑铭位置的。

**Comment by nierssaxa** [comment]
### 首页等单页优化
1.鼠标移入书籍时，书名不再放大
2.单页依旧要加上分类名，列表和卡片的切换按钮做在与分类名同行最右侧（即便是单页也要保持首页的样式大致相同）
![2IB%5MIJ}NCBNXMZMM`CE6Q](https://user-images.githubusercontent.com/97571785/224516584-ec12eb82-9ebe-405c-aca2-7b568e020ab2.png)

**Comment by nierssaxa** [comment]
### 单页优化part.2
1.下方加载更多做宽度自适应
![77KQ%K03$(0MV_C`FG2W1T1](https://user-images.githubusercontent.com/97571785/224584492-6065da68-a629-4f58-98f3-958ee1bfb725.png)
2.展示模式切换的按钮，注意跟随书籍种类切换颜色（不要统一用橙色）。

**Comment by nierssaxa** [comment]
### 首页优化part.2
1.最近阅读标题右侧，新增清除记录（样式与查看全部相同）
2.清除记录记得弹窗二次确认，确认清除后设定重新载入页面
3.最近阅读也可以做成左右切换

**Comment by nierssaxa** [comment]
### 内页优化part.2
1.若判定套书有成就，则在套书名字右侧10px的位置，新增一个按钮，点击后跳转到对应成就（注意按钮和文字水平对齐）
![~TO(4Y`GT2M 0I329WXA(73](https://user-images.githubusercontent.com/97571785/224585250-bf111701-a09b-48b1-b2a9-cfbd98ef7ac0.png)
2.书籍内容的切换按钮，当到底或到顶时，对应不可点的按钮应当透明度50%。
3.注意确认白色箭头是否在底图正中央，如果对齐麻烦 可以使用群内的svg文件。
4.书籍内容的切换按钮，应当长期有个阴影
box-shadow: 0px 0px 10px rgba(50, 65, 72, 0.4)
此处的10为blur，x和y为0

**Comment by fifthThirteen** [comment]
> ### 单页优化part.2
> 1.下方加载更多做宽度自适应 ![77KQ%K03$(0MV_C`FG2W1T1](https://user-images.githubusercontent.com/97571785/224584492-6065da68-a629-4f58-98f3-958ee1bfb725.png) 2.展示模式切换的按钮，注意跟随书籍种类切换颜色（不要统一用橙色）。

![image](https://user-images.githubusercontent.com/30660189/224936511-de6f1bb7-6dea-42b2-a26f-b5ddf8949c7d.png)
加载更多计算了当前宽度的，有自适应，但是没有resize，也就是你变化窗口没去改变这个宽度，暂时不做，用户用不到

**Comment by fifthThirteen** [comment]
> 

最近阅读以及其他三类都做了超过当前行的宽度就会变成切换，没超过就不会显示滚动按钮。

**Comment by fifthThirteen** [comment]
> ### 内页优化part.2
> 1.若判定套书有成就，则在套书名字右侧10px的位置，新增一个按钮，点击后跳转到对应成就（注意按钮和文字水平对齐） ![~TO(4Y`GT2M 0I329WXA(73](https://user-images.githubusercontent.com/97571785/224585250-bf111701-a09b-48b1-b2a9-cfbd98ef7ac0.png) 2.书籍内容的切换按钮，当到底或到顶时，对应不可点的按钮应当透明度50%。 3.注意确认白色箭头是否在底图正中央，如果对齐麻烦 可以使用群内的svg文件。 4.书籍内容的切换按钮，应当长期有个阴影 box-shadow: 0px 0px 10px rgba(50, 65, 72, 0.4) 此处的10为blur，x和y为0

套书名称右侧目前是有成就名称及链接的，确定是否将套书成就名称改为以上文字内容？
