### ISSUE TITLE
技艺助手新版

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#88]
https://www.figma.com/file/O5450TSGCIf9aEvp3mojdo/JX3BOX-PVX?node-id=59%3A552&t=vcxnJpbE0QqoIeRE-0

下面的部分，稍微根据设计稿优化一下

头部有调整，注意跟pvx库其他的保持相似

适配自己要看

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/a88262c9-48c8-426d-903e-751f0e2048ee)
![image](https://github.com/JX3BOX/pvx/assets/30660189/9c87282e-6418-48a6-b6ee-c5291cbcc96f)
ipad和phone模式下样式适配

**Comment by fifthThirteen** [comment]
我的清单模块的相关接口 判断登录之后再请求，没登录可以不显示或显示登录按钮

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/50e49685-8da0-478e-852a-b4b4de378d84)
购物车按钮点击后没关联左侧和中间的数字框

三个按钮和框是否太过重复了？

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/dc89d09d-804b-4c75-ba0b-e2ca5998ea38)
修改价格关联一下

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/9f8575c7-2d3c-4371-9485-65232293d29e)
![image](https://github.com/JX3BOX/pvx/assets/30660189/020d6d09-966d-47ec-a40e-c3853865f2d1)

死循环了，瞅一瞅

**Comment by fifthThirteen** [comment]
![image](https://github.com/JX3BOX/pvx/assets/30660189/cb2b4c8e-680f-46b5-bdc8-419e3e0189a1)
1. 创建清单后没有自动更新
2. 是否增加编辑清单和删除清单

**Comment by zixuan1986** [comment]
> ![image](https://user-images.githubusercontent.com/30660189/239938280-a88262c9-48c8-426d-903e-751f0e2048ee.png) ![image](https://user-images.githubusercontent.com/30660189/239938376-9c87282e-6418-48a6-b6ee-c5291cbcc96f.png) ipad和phone模式下样式适配

需胧月提供手机版本下的样式适配
