### ISSUE TITLE
新版金价与物价合并为价格走势

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#90]
## 背景介绍
当前线上有一个物价大全 https://www.jx3box.com/pvg/item_price
还有一个金价走势 https://www.jx3box.com/app/price/
这次计划合并二者为一个“金价走势”的应用。

- [ ] 已完成

**Comment by iRuxu** [comment]
## 原型稿
https://www.figma.com/file/O5450TSGCIf9aEvp3mojdo/JX3BOX-PVX?node-id=88%3A16&t=mtUak2VqBPRjMv4T-1

- [ ] 已完成

**Comment by iRuxu** [comment]
## 入口
文件：views/price，对应文件都写在该文件夹下
路由：/pvg/price

<img width="591" alt="image" src="https://user-images.githubusercontent.com/8476969/224437801-4f193ad8-8583-41f2-bbc6-26db20f50059.png">
公共部分可参考/src/components/PvxSearch.vue

- [ ] 已完成

**Comment by iRuxu** [comment]
## 金价
<img width="929" alt="image" src="https://user-images.githubusercontent.com/8476969/224437225-1f672bfb-4a21-41de-bd96-94ea7302e7aa.png">

接口文档：https://spider2.jx3box.com/docs

+ 接口：受姐姐
+ 设计：胧月

- [ ] 已完成

**Comment by iRuxu** [comment]
## 物价
参考现有的物价页
在views/pvg/Item.vue
<img width="786" alt="image" src="https://user-images.githubusercontent.com/8476969/224438776-c82a9d8d-bf2a-4d88-ae1a-25321c1c4601.png">

+ 接口：小胡
+ 设计：胧月

- [ ] 已完成

**Comment by iRuxu** [comment]
## 首页
<img width="925" alt="image" src="https://user-images.githubusercontent.com/8476969/224437598-6d30aaf9-ccbf-4c94-9c87-6956a7d364f1.png">

1. 走势，同金价部分
2. 我的关注：同物价，只是请求的列表id是自定义的（楼下补充）
3. 热门列表：同物价，先任意请求物价的一个，回头会追加一个热门列表

- [ ] 已完成

**Comment by iRuxu** [comment]
## 我的关注
指定展示某几个清单即可，再拉取到清单中所有物品的id，再批量请求

展示清单
GET `https://cms.jx3box.com/api/cms/user/my/meta?key=focus_price`

POST `https://cms.jx3box.com/api/cms/user/my/meta?key=focus_price`
```json
{
val : 1,2,3
}
```

**Comment by iRuxu** [comment]
## 服务器UI问题：
<img width="720" alt="image" src="https://user-images.githubusercontent.com/8476969/235469028-2fb61e76-0e5e-40b2-98d0-e5fd1c23b72e.png">

- [x] 已完成

**Comment by iRuxu** [comment]
## TAB切换
<img width="719" alt="image" src="https://user-images.githubusercontent.com/8476969/235469178-39c2b204-3f82-4483-b166-180dc19e919f.png">

增加路由同步，方便复制出去地址

- [x] 已完成

**Comment by iRuxu** [comment]
## 服务器列表
<img width="398" alt="image" src="https://user-images.githubusercontent.com/8476969/235469319-e250d4f8-fc45-4c0b-ac0e-fcf17581a3ec.png">

金价只能使用 cn列表，也就是国服
物价使用std列表，代表国服+国际服

- [x] 已完成

**Comment by iRuxu** [comment]
## 安全警告
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/8476969/235469613-2b2a6d6a-ed25-4e2d-9569-49769261398a.png">
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/8476969/235469657-8c69bfa2-7d57-4981-b36b-eb3ad34841a8.png">

- [x] 已完成

**Comment by iRuxu** [comment]
## 头部位置
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/8476969/235477192-3bcdca2d-d1f2-4d9a-8aa5-a9c3aac52fe2.png">

- [x] 已完成

**Comment by iRuxu** [comment]
## 物价接口（blank）

根据一批物品id查询物价

## 批量查询昨日物价

```
URL: https://next2.jx3box.com/api/item-price/list
Method: GET
Query:
    itemIds: "1_11,2_22',  物品ID 使用,隔开
    server: "乾坤一掷"    服务器名称

Response: 
// 例如: https://next2.jx3box.com/api/item-price/list?itemIds=5_41168&server=%E5%89%91%E8%83%86%E7%90%B4%E5%BF%83
{
    "code": 0,
    "msg": "",
    "data": {
        "5_41168": {
            "ID": 64665,
            "ItemId": "5_41168",
            "Server": "剑胆琴心",
            "Lang": 1,
            "LowestPrice": 34007400,
            "AvgPrice": 34007400,
            "HighestPrice": 34007400,
            "SampleSize": 2493,
            "Date": "2022-07-14",
            "CreatedAt": "2022-07-14T20:15:04+08:00",
            "UpdatedAt": "2022-07-14T23:16:55+08:00"
        }
    }
}
```

**Comment by iRuxu** [comment]
## 我的清单接口（醉栩）

```
URL: https://cms.jx3box.com/api/cms/app/item_plans/mine
Method: GET
Query:
- page 页码
- per 单页条数

Response:
// https://cms.jx3box.com/api/cms/api/cms/app/item_plans/mine?page=1&per=10
{
    "code": 0,
    "msg": "Success",
    "data": {
        "total": 2,
        "per": 10,
        "pages": 1,
        "page": "1",
        "list": [
            {
                "id": 763,
                "user_id": 8719,
                "public": 0,
                "title": "物品清单测试",
                "type": 1,
                "description": "",
                "relation": [
                    {
                        "data": [
                            {
                                "id": "10_10",
                                "Name": "麦仙翁",
                                "UiID": 164671,
                                "count": 1,
                                "IconID": 13469,
                                "Quality": 3,
                                "AucGenre": "21",
                                "DescHtml": "<span>此物初非本朝原生种属，概为长安白氏引入培育。<br></span>",
                                "AucSubType": "3"
                            },
                            {
                                "id": "10_100",
                                "Name": "赤漆药柜",
                                "UiID": 164593,
                                "count": 1,
                                "IconID": 13468,
                                "Quality": 1,
                                "AucGenre": "21",
                                "DescHtml": "<span>赤漆涂，或曰罩朱单漆。素木地以赤红苏木汁染，罩涂揩清漆一层，尔后揩清、推光，成器则木纹与漆色相映，光华耀目。<br></span>",
                                "AucSubType": "2"
                            },
                            {
                                "id": "10_1000",
                                "Name": "不钓名",
                                "UiID": 258799,
                                "count": 1,
                                "IconID": 13531,
                                "Quality": 4,
                                "AucGenre": "21",
                                "DescHtml": "<span>垂钓池鱼，不钓名。<br>该物件的养鱼交互仅在私邸宅园可用<br></span>",
                                "AucSubType": "4"
                            },
                            { "id": "5_18812", "count": 1 }
                        ],
                        "title": ""
                    }
                ],
                "created": 1683192797,
                "updated": 1683192797,
                "deleted": 0,
                "user_info": { "display_name": "醉栩", "user_avatar": "https://oss.jx3box.com/upload/avatar/2022/12/11/8719_8836198.jpg" }
            }
        ]
    }
}

```

**Comment by iRuxu** [comment]
## 设置关注清单（醉栩）
key=follow_price
val=清单ID

指定展示某几个清单即可，再拉取到清单中所有物品的id，再批量请求

展示清单
GET `https://cms.jx3box.com/api/cms/user/my/meta?key=focus_price`

POST `https://cms.jx3box.com/api/cms/user/my/meta?key=focus_price`
```json
{
val : 1,2,3
}
```

**Comment by iRuxu** [comment]
## 物价请求

### 根据关注清单请求物价

### 根据公共物品集合请求物价

公共物品集合接口：

```
URL: https://cms.jx3box.com/api/cms/helper/item/group
Method: GET
Query:
key: string 对应集合的key，多个则用半角逗号隔开

例子: https://cms.jx3box.com/api/cms/helper/item/group?key=wuxingshi,qita

Response:
{
    "code": 0,
    "msg": "Success",
    "data": [
        {
            "id": 1,
            "key": "wuxingshi",
            "label": "五行石",
            "description": "",
            "items": [
                {
                    "icon": 7523,
                    "label": "五行石（一级）",
                    "remark": "",
                    "item_id": "5_24423"
                },
                {
                    "icon": 7524,
                    "label": "五行石（二级）",
                    "remark": "",
                    "item_id": "5_24424"
                },
                {
                    "icon": 7525,
                    "label": "五行石（三级）",
                    "remark": "",
                    "item_id": "5_24425"
                },
                {
                    "icon": 7526,
                    "label": "五行石（四级）",
                    "remark": "",
                    "item_id": "5_24426"
                },
                {
                    "icon": 7528,
                    "label": "五行石（六级）",
                    "remark": "",
                    "item_id": "5_24428"
                },
                {
                    "icon": 7527,
                    "label": "五行石（五级）",
                    "remark": "",
                    "item_id": "5_24427"
                },
                {
                    "icon": 7529,
                    "label": "五行石（七级）",
                    "remark": "",
                    "item_id": "5_24429"
                },
                {
                    "icon": 7530,
                    "label": "五行石（八级）",
                    "remark": "",
                    "item_id": "5_24430"
                }
            ],
            "sort": 10,
            "creator_id": 1,
            "created": 1625924728,
            "updated": 1661788888,
            "deleted": 0
        },
        {
            "id": 24,
            "key": "qita",
            "label": "其他",
            "description": "",
            "items": [
                {
                    "icon": 13092,
                    "label": "沉夜素·臻",
                    "remark": "",
                    "item_id": "5_35044"
                },
                {
                    "icon": 13091,
                    "label": "寒信素·臻",
                    "remark": "",
                    "item_id": "5_35007"
                },
                {
                    "icon": 13094,
                    "label": "曦晖素·臻",
                    "remark": "",
                    "item_id": "5_35006"
                },
                {
                    "icon": 13095,
                    "label": "鸦青素·臻",
                    "remark": "",
                    "item_id": "5_35005"
                },
                {
                    "icon": 13093,
                    "label": "红荣素·臻",
                    "remark": "",
                    "item_id": "5_35004"
                },
                {
                    "icon": 13092,
                    "label": "沉夜素·浓",
                    "remark": "",
                    "item_id": "5_35003"
                },
                {
                    "icon": 13091,
                    "label": "寒信素·浓",
                    "remark": "",
                    "item_id": "5_35002"
                },
                {
                    "icon": 13094,
                    "label": "曦晖素·浓",
                    "remark": "",
                    "item_id": "5_35001"
                },
                {
                    "icon": 13095,
                    "label": "鸦青素·浓",
                    "remark": "",
                    "item_id": "5_35000"
                },
                {
                    "icon": 13093,
                    "label": "红荣素·浓",
                    "remark": "",
                    "item_id": "5_34999"
                },
                {
                    "icon": 962,
                    "label": "素冠荷鼎",
                    "remark": "",
                    "item_id": "5_11111"
                }
            ],
            "sort": 14,
            "creator_id": 9,
            "created": 1661789255,
            "updated": 1661789255,
            "deleted": 0
        }
    ]
}

```

**Comment by nierssaxa** [comment]
![F (}4ED@A}CUIPG)F%I8)2](https://user-images.githubusercontent.com/97571785/235495772-10e33a0b-1ac9-4dfb-90c8-6605ddfa3202.png)
1.上下边距和左右边距理应都是10px
![I4H1R2UL)~DU_~N3P1{06_N](https://user-images.githubusercontent.com/97571785/235496127-3ad72007-9127-467a-98f1-26efe87cc63f.png)
2.图标没有水平对齐

- [ ] 已完成

**Comment by nierssaxa** [comment]
![SMVEMZPFF1FCZ%FZ@PA{_(G](https://user-images.githubusercontent.com/97571785/235496329-944dea6f-8eb6-4229-8182-2a26a3cfe5a0.png)
与侧边栏的间距问题，
三种情况下的间距，参考捏脸

- [x] 已完成

**Comment by Kaviilee** [comment]
## 移动端适配

金价未进行移动端适配
![image](https://user-images.githubusercontent.com/25825282/236105199-328628e3-6471-4fe0-8171-9c4674e8a954.png)

- [x] 已完成

**Comment by Kaviilee** [comment]
## 代码相关
1. 不需要自己再封装axios，意味着 service/api.js 和 service/request.js 是不需要的，参照 service/face.js 
![image](https://user-images.githubusercontent.com/25825282/236124251-ea7831b2-d315-4520-930b-3d4d48687d30.png)

- [ ] 已完成

2. axios返回的已经是 promise 对象，不需要再用 promise 包一层
![image](https://user-images.githubusercontent.com/25825282/236124796-4d44421e-f04b-4423-a0e7-01e9385cb0fc.png)

- [ ] 已完成

3. 请求逻辑不要放在 vue 文件，要单独在 service 内，参照其他 service 内文件的写法
![image](https://user-images.githubusercontent.com/25825282/236125972-7651d840-f8dc-4179-9e89-e4c307de3363.png)

- [ ] 已完成

4. 样式名称写法需要修改 参照 [前端命名规范](https://github.com/JX3BOX/styleguide/blob/master/HTML%E4%B8%8ECSS%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83.md)

- [ ] 已完成

**Comment by iRuxu** [comment]
## 获取预设物品集合

cms.jx3box.com/api/cms/helper/item_groups

- [ ] 已完成

**Comment by iRuxu** [comment]
## 物价页面

### 旧接口
http://localhost:8081/api/item-groups/with-prices?server=%E8%9D%B6%E6%81%8B%E8%8A%B1&limit=18
<img width="455" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/e0e4fd71-7910-4bd3-9c9c-07b50297e99c">

### 拿到物品
第一步，先请求拿到所有系统关注的物品
https://cms.jx3box.com/api/cms/helper/item/group?key=baoxiang,caijincailiao

### 拿到物价
第二步，拿到对应服务器的物价
```
URL: https://next2.jx3box.com/api/item-price/list
Method: GET
Query:
    itemIds: "1_11,2_22',  物品ID 使用,隔开
    server: "乾坤一掷"    服务器名称

Response: 
// 例如: https://next2.jx3box.com/api/item-price/list?itemIds=5_41168&server=%E5%89%91%E8%83%86%E7%90%B4%E5%BF%83
{
    "code": 0,
    "msg": "",
    "data": {
        "5_41168": {
            "ID": 64665,
            "ItemId": "5_41168",
            "Server": "剑胆琴心",
            "Lang": 1,
            "LowestPrice": 34007400,
            "AvgPrice": 34007400,
            "HighestPrice": 34007400,
            "SampleSize": 2493,
            "Date": "2022-07-14",
            "CreatedAt": "2022-07-14T20:15:04+08:00",
            "UpdatedAt": "2022-07-14T23:16:55+08:00"
        }
    }
}
```

- [ ] 已完成

**Comment by iRuxu** [comment]
## 首屏

### 鉴权逻辑：
1. 判断是否已登录
2. 如果已登录
    2.1 如果已经有关注清单，就根据关注清单请求物价
    2.2 如果没有关注清单，先选择你需要关注的清单，然后回到2.1


### 拉取你自己的所有清单
```
URL: https://cms.jx3box.com/api/cms/app/item_plans/mine
Method: GET
Query:
- page 页码
- per 单页条数

Response:
// https://cms.jx3box.com/api/cms/api/cms/app/item_plans/mine?page=1&per=10
{
    "code": 0,
    "msg": "Success",
    "data": {
        "total": 2,
        "per": 10,
        "pages": 1,
        "page": "1",
        "list": [
            {
                "id": 763,
                "user_id": 8719,
                "public": 0,
                "title": "物品清单测试",
                "type": 1,
                "description": "",
                "relation": [
                    {
                        "data": [
                            {
                                "id": "10_10",
                                "Name": "麦仙翁",
                                "UiID": 164671,
                                "count": 1,
                                "IconID": 13469,
                                "Quality": 3,
                                "AucGenre": "21",
                                "DescHtml": "<span>此物初非本朝原生种属，概为长安白氏引入培育。<br></span>",
                                "AucSubType": "3"
                            },
                            { "id": "5_18812", "count": 1 }
                        ],
                        "title": ""
                    }
                ],
                "created": 1683192797,
                "updated": 1683192797,
                "deleted": 0,
                "user_info": { "display_name": "醉栩", "user_avatar": "https://oss.jx3box.com/upload/avatar/2022/12/11/8719_8836198.jpg" }
            }
        ]
    }
}

```

### 选择并设置关注清单

key=`follow_inventory`
val=`123`（清单ID）

POST `https://cms.jx3box.com/api/cms/user/my/meta?key=follow_inventory`
```json
{
val : 123
}
```

### 获取我关注的是哪一个清单
GET `https://cms.jx3box.com/api/cms/user/my/meta?key=follow_inventory`
val : 123

### 请求对应的这个清单详情
GET `https://cms.jx3box.com/api/cms/app/item_plan/188`

**Comment by iRuxu** [comment]
## 服务器

1. 没有登录 - > 默认服务器：梦江南
2. 已登录 - > 
     2.1 是否有设置资料服务器 -> 有就用，没有就还是使用默认服务器
https://cms.jx3box.com/api/cms/user/my/info

`jx3_server`

- [ ] 已完成

**Comment by iRuxu** [comment]
## 物价页面
![5588db4ae48038d8d8ebc66730b0724e](https://github.com/JX3BOX/pvx/assets/8476969/6aca89a5-0eea-4d58-843f-a5a567795be3)
不需要再展示我的关注

- [x] 已完成

**Comment by iRuxu** [comment]
## 物价页面
不要展示所有key啊，按原来的来。
怀旧服没有物价。
只请求下面的key
![image](https://github.com/JX3BOX/pvx/assets/8476969/c642148b-03b8-4350-8764-641e01695256)

<img width="359" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/93085d7d-6470-4737-92ec-e8a0cff297aa">
<img width="430" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/53e91756-f617-48e1-8f0c-f52ff9b39244">
<img width="366" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/cd3cb01c-4c78-4e64-bc44-fe6993259089">
<img width="432" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/dd7c8e6c-53ca-4d8a-9173-13f3b7e90d20">
<img width="472" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/4f2f6c90-6609-4240-97d7-94139d72069e">
<img width="536" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/b70cec81-e54f-414c-9666-e4eb850e4a0b">

- [x] 已完成

**Comment by iRuxu** [comment]
## 未登录
<img width="790" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/539757f8-62f5-4f44-a432-ac663a2575fe">

- [x] 已完成

**Comment by iRuxu** [comment]
## 适配
<img width="580" alt="image" src="https://github.com/JX3BOX/pvx/assets/8476969/9770313e-bc33-4c45-91e5-db419aca732a">

- [x] 已完成

**Comment by iRuxu** [comment]
## 清单列表窗口
假设没有清单，给个提示

你还没有创建任何清单，点击创建
/item

- [x] 已完成
