### ISSUE TITLE
地图组件局部展示

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvx_v1#94]

**Comment by nierssaxa** [comment]
要求：原地图不缩放的前提下，以坐标点为中心，截取所需大小区域。
（如下图，黑色为地图800x800，红点为固定坐标点，灰色为截取范围480x300）
![Frame 1](https://user-images.githubusercontent.com/97571785/224455738-9148d4e7-abe6-4a4c-aebf-7bfa301475cb.jpg)

**Comment by nierssaxa** [comment]
特殊情况：如果固定点（红点），位于地图边缘（无法以该点为中心做局部展示），则自动向其他方向取区域。
如下图，左侧和下侧距离不够，则向右和向上取区域
![Frame 1](https://user-images.githubusercontent.com/97571785/224456065-589c787b-dbbb-4df2-ac7f-fb4f183eaec1.jpg)

**Comment by nierssaxa** [comment]
由于采用局部展示的原因，地图名字考虑做在悬浮固定点（红点）时出现的信息框上。

由原来的：
触发点
坐标：(17870,30760,1057792)
NPC：47992

↓

变更为：
触发点
**地图：洛道**
坐标：(17870,30760,1057792)
NPC：47992
